name: Subir log

on:
    push:
        branches:
            - master

jobs:
    conexion-ssh:
        runs-on: ubuntu-latest
        steps:
            - name: Instalar sshpass
              run: sudo apt-get update && sudo apt-get install -y sshpass
            - name: Conectar por SSH
              run: |
                sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.IP }} "
                echo 'Conexión exitosa'
