name: Hola Mundo

on: 
  push:
        branches:
            - master
jobs:
    hola:
        runs-on: ubuntu-latest
        steps:
              - name:
                run: echo "Hola Mundo"
              - name: Instalar figlet
                run: sudo apt-get install install figlet
              - name: Usar figlet
                run: figlet "Hola mundo"