name: Nmap SSH

on: 
  push:
      branches:
          - master
jobs:
    hola:
        runs-on: ubuntu-latest
        steps:
            - name: Descargar sshpass
              run: sudo apt-get update && sudo apt-get install sshpass -y
            - name: Usar sshpass
              run: sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.IP }} "echo 'Conexión exitosa'"